# Generated by Django 4.1.7 on 2023-03-17 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('pic', models.ImageField(blank=True, upload_to=user.models.PathAndRename('hospital/'), verbose_name='Hospital_Profile_Pic')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('hospital', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pic',
            field=models.ImageField(blank=True, upload_to=user.models.PathAndRename('patient/'), verbose_name='Patient_Profile_Pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOSPITAL', 'Hospital'), ('PATIENT', 'Patient')], max_length=50),
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
