# Generated by Django 4.1.7 on 2023-04-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_hospitalprofile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.PathAndRename('patient/'), verbose_name='Patient_Profile_Pic'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
