# Generated by Django 4.1.7 on 2023-05-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreview',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_review', to='user.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_review_as_patient', to='user.patient'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review_as_patient', to='user.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='user.hospital'),
        ),
    ]
