# Generated by Django 4.1.7 on 2023-06-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coreapp', '0002_alter_appointment_doctor_alter_appointment_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_appointment', to='user.hospitalprofile'),
        ),
    ]
