# Generated by Django 4.1.7 on 2023-05-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreview',
            name='doctor_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreview',
            name='hospital_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
