# Generated by Django 4.1.7 on 2023-05-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('doctor_review', models.TextField(blank=True, null=True)),
                ('hospital_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('hospital_review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_review', to='coreapp.appointment')),
            ],
        ),
    ]
